name: vispool
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python >=3.11.0,<3.12
  - pytorch>=2.1.1
  - pytorch-cuda=11.8
  - lightning
  - transformers
  - datasets
  - evaluate
  - numba
  - numpy
  - python-dotenv
  - scikit-learn
  - wandb
